# Generated by Django 5.2.4 on 2025-07-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandPortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='name',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='first_name',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='last_name',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default='sd', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
