# Generated by Django 5.2.4 on 2025-07-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandPortfolioApp', '0002_remove_contactmessage_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
